name: project-name

services:
  app:
    image: yovanggaanandhika/microservices-core-enterprise:latest-mongo-8.0.5
    container_name: project-name-app
    hostname: project-name-app
    pull_policy: always
    restart: always
    environment:
      DKA_REPL_ENABLED: true
    deploy:
      resources:
        reservations:
          memory: 500M
        limits:
          memory: 800M
    ports:
      # expose by wan external public
      - target: 50051
        published: 50051
        protocol: tcp
        host_ip: 0.0.0.0
    networks:
      - project-name

networks:
  project-name:
    driver: bridge