name: project-name

services:
  app:
    image: yovanggaanandhika/node:latest
    container_name: project-name-app
    hostname: project-name-app
    pull_policy: always
    restart: always
    environment:
      DKA_PG_HOST: dka-dev-postgresql
      DKA_MONGO_HOST: dka-dev-mongo
      # Servicing Scope Url #
      DKA_SERVICE_ACCOUNT_HOST: dka-services-core-account-app
      DKA_SERVICE_ENTERPRISE_HOST: dka-services-core-enterprise-app
    ports:
      # expose by wann external public
      - target: 50051
        published: 50052
        protocol: tcp
        host_ip: 0.0.0.0
    volumes:
      - type: tmpfs
        target: /home/app/dist
      - type: bind
        source: .
        target: /home/app
    deploy:
      resources:
        reservations:
          memory: 1028M
        limits:
          memory: 2048M
    command: yarn run start:dev
    networks:
      - dka-development-network

networks:
  dka-development-network:
    name: dka-development-network
    external: true
