name: dka-services-core-enterprise

services:
  app:
    image: yovanggaanandhika/microservices-core-enterprise:latest-mongo-8.0.5
    container_name: dka-services-core-enterprise-app
    hostname: dka-services-core-enterprise-app
    pull_policy: always
    restart: always
    environment:
      DKA_REPL_ENABLED: true
    deploy:
      resources:
        reservations:
          memory: 500M
        limits:
          memory: 800M
    ports:
      # expose by wan external public
      - target: 50051
        published: 50052
        protocol: tcp
        host_ip: 0.0.0.0
      # expose by internal kubernetes
      - target: 80
        published: 8082
        protocol: tcp
        host_ip: 0.0.0.0
      - target: 27017
        published: 27018
        protocol: tcp
        host_ip: 0.0.0.0
    volumes:
      - type: volume
        source: dka-services-core-enterprise-mongo-data
        target: /data/db
    networks:
      - dka-services-core-enterprise

volumes:
  dka-services-core-enterprise-mongo-data:
    name : dka-services-core-enterprise-mongo-data
    driver: local

networks:
  dka-services-core-enterprise:
    driver: bridge