name: Action Prod CI/CD

on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod

env:
  TAG_NAME: latest

jobs:
  build-native:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DKA_DOCKER_USERNAME }}
          password: ${{ secrets.DKA_DOCKER_TOKEN }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DKA_DOCKER_USERNAME }}/${{ secrets.DKA_DOCKER_REPO }}:${{ env.TAG_NAME }}

  build-with-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DKA_DOCKER_USERNAME }}
          password: ${{ secrets.DKA_DOCKER_TOKEN }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./mongo.Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DKA_DOCKER_USERNAME }}/${{ secrets.DKA_DOCKER_REPO }}:${{ env.TAG_NAME }}-mongo-8.0.5